version: "3"
services:
  train_test_pipeline:
    build:
      context: .
      dockerfile: './docker/DockerfileDev'
    ports:
      - "7000:7000"
  inference_pipeline:
    build:
      context: .
      dockerfile: './docker/Dockerfile'
    ports:
      - "8000:8000"
